name: Github Actions 실행시켜보기 # Workflow 이름

# Event : 실행되는 시점을 설정
# main 이라는 브렌치에 push 될때 아래 Workflow 실행
on:
  push:
    branches:
      - main

# 하나의 workflow는 1개 이상의 Job으로 구성된다.
# 여러 job은 기본적으로 병렬적으로 수행된다.
jobs:
  # Job을 식별하기 위한 Id
  My-Deploy-Job:
    # Ubuntu 최신버전
    runs-on: ubuntu-latest

    # step : 특정 작업을 수행하는 가장 작은 단위
    # Job : 여러 Step 으로 구성되어 있다.
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run : |
          echo "Good"
          echo "Nice"